### ISSUE TITLE
No module named 'mighty.utils.var_online'

### ISSUE THREAD

**Issue by GraceZhuuu** [dizcza/pytorch-mighty#1]
Thanks for your work.   

i used it then occured a error "No module named 'mighty.utils.var_online'".
i checked the site-packages 
```
~/anaconda3/envs/sparse/lib/python3.9/site-packages/mighty/utils                       py sparse 15:22:37
> ls
common.py     data       hooks.py     prepare.py   signal.py
constants.py  domain.py  __init__.py  __pycache__  stub.py

```

**Comment by dizcza** [comment]
I've just published a new release with a fix, try updating the package

```
pip install --upgrade pytorch-mighty
```

**Comment by dizcza** [comment]
I've been using my pytorch-mighty package for over 5+ years; I developed it because at that time Pytorch Horovod wasn't even there. I'm still using it as it fits nicely into my research area, though I do find it limited in other aspects like audio processing, for example.

How do you use it?

**Comment by GraceZhuuu** [comment]
> I've been using my pytorch-mighty package for over 5+ years; I developed it because at that time Pytorch Horovod wasn't even there. I'm still using it as it fits nicely into my research area, though I do find it limited in other aspects like audio processing, for example.
> 
> How do you use it?

I'm a newbie in the image compression direction and I use it from your another project "sparse-representation".
Still in the learning phase, thanks for your help !

**Comment by dizcza** [comment]
All right, did it solve your issue?

**Comment by GraceZhuuu** [comment]
> All right, did it solve your issue?

This issue is solved, but i met another one in "sparse-representation" which i am trying to solve it.
Thanks again.

**Comment by dizcza** [comment]
All right, feel free to open an issue there if you don't manage to solve it by yourself.
